"""
Generate infra/sql/08_fix_media_seed.sql — run from the repo root:

    cd civikta
    python -m infra.generate_media_seed > infra/sql/08_fix_media_seed.sql

Or run directly (adjust sys.path if needed):
    python infra/generate_media_seed.py
"""

import sys
import os

# Allow importing from services/api/app
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "services", "api"))

from app.seeds.demo_issues import build_demo_issues

lines = [
    "-- AUTO-GENERATED by infra/generate_media_seed.py -- do not edit by hand",
    "-- Run in Supabase SQL editor AFTER 01_schema.sql and 02_seed_demo.sql",
    "",
    "-- 1. Add cover_media_url column if not exists",
    "ALTER TABLE public.issues ADD COLUMN IF NOT EXISTS cover_media_url text;",
    "",
    "-- 2. Link original reports to their canonical issues",
    "UPDATE public.issue_reports ir",
    "SET merged_into_issue_id = i.id",
    "FROM public.issues i",
    "WHERE ir.id = i.original_report_id",
    "  AND ir.merged_into_issue_id IS NULL;",
    "",
    "-- 3. Insert issue_media rows (idempotent via ON CONFLICT DO NOTHING)",
]

demo = list(build_demo_issues())

for issue, report, media_list, _ in demo:
    for m in media_list:
        url = m.storage_url.replace("'", "''")
        ts = m.created_at.strftime("%Y-%m-%dT%H:%M:%S.%f") + "Z"
        lines.append(
            f"INSERT INTO public.issue_media(id, report_id, media_type, storage_url, created_at) "
            f"VALUES('{m.id}', '{m.report_id}', 'image', '{url}', '{ts}') ON CONFLICT DO NOTHING;"
        )

lines += [
    "",
    "-- 4. Populate cover_media_url on issues from first media of original report",
    "UPDATE public.issues i",
    "SET cover_media_url = m.storage_url",
    "FROM public.issue_media m",
    "JOIN public.issue_reports r ON r.id = m.report_id",
    "WHERE r.id = i.original_report_id",
    "  AND i.cover_media_url IS NULL",
    "  AND m.id = (",
    "    SELECT id FROM public.issue_media",
    "    WHERE report_id = r.id",
    "    ORDER BY created_at",
    "    LIMIT 1",
    "  );",
]

print("\n".join(lines))
